document.write("<table>");
document.write("<tr>");
document.write("<td class=\"banner\"><img src=\"images/bill_lumbergh.jpg\" alt=\"\" title=\"Bill Lumbergh\" onclick=\"playSound('sounds/bill_lumbergh.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/david_brent.jpg\" alt=\"\" title=\"David Brent\" onclick=\"playSound('sounds/david_brent.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/blake.jpg\" alt=\"\" title=\"Blake\" onclick=\"playSound('sounds/blake.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/franklin_hart.jpg\" alt=\"\" title=\"Franklin M. Hart Jr.\" onclick=\"playSound('sounds/franklin_hart.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/pointy_haired_boss.jpg\" alt=\"\" title=\"Pointy-haired Boss\" onclick=\"playSound('sounds/pointy_haired_boss.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/gordon_gekko.jpg\" alt=\"\" title=\"Gordon Gekko\" onclick=\"playSound('sounds/gordon_gekko.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/louie_de_palma.jpg\" alt=\"\" title=\"Louie De Palma\" onclick=\"playSound('sounds/louie_de_palma.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/katharine_parker.jpg\" alt=\"\" title=\"Katharine Parker\" onclick=\"playSound('sounds/katharine_parker.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/michael_scott.jpg\" alt=\"\" title=\"Michael Scott\" onclick=\"playSound('sounds/michael_scott.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/miranda_priestly.jpg\" alt=\"\" title=\"Miranda Priestly\" onclick=\"playSound('sounds/miranda_priestly.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/douglas_reynholm.jpg\" alt=\"\" title=\"Douglas Reynholm\" onclick=\"playSound('sounds/douglas_reynholm.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/paula.jpg\" alt=\"\" title=\"Paula\" onclick=\"playSound('sounds/paula.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/donald_trump.jpg\" alt=\"\" title=\"Donald Trump\" onclick=\"playSound('sounds/donald_trump.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/montgomery_burns.jpg\" alt=\"\" title=\"Montgomery Burns\" onclick=\"playSound('sounds/montgomery_burns.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/j_peterman.jpg\" alt=\"\" title=\"J. Peterman\" onclick=\"playSound('sounds/j_peterman.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/j_r_ewing.jpg\" alt=\"\" title=\"J. R. Ewing\" onclick=\"playSound('sounds/j_r_ewing.mp3');\" /></td>");
document.write("<td class=\"banner\"><img src=\"images/gordon_ramsay.jpg\" alt=\"\" title=\"Gordon Ramsay\" onclick=\"playSound('sounds/gordon_ramsay.mp3');\" /></td>");
document.write("</tr>");
document.write("</table>");